# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Mulo`s Blog
tagline:             'A Jekyll theme'
description:         'a simple'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              chenxuqi
  email:             chenxuqi876@gmail.com

# Custom vars
version:             1.0.0
